# Generated by Django 5.2.3 on 2025-06-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('profit_percent', models.FloatField()),
                ('min_deposit', models.BigIntegerField()),
                ('max_deposit', models.BigIntegerField()),
                ('min_return_percent', models.FloatField(default=0.0)),
                ('max_return_percent', models.FloatField()),
                ('bonus', models.BigIntegerField(default=0)),
            ],
        ),
    ]
