# Generated by Django 5.2.3 on 2025-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0002_paymentmethods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc', models.BooleanField(default=False)),
                ('verification', models.BooleanField(default=False)),
            ],
        ),
    ]
