# Generated by Django 5.2.3 on 2025-06-24 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 17, 50, 15, 760665, tzinfo=datetime.timezone.utc)),
        ),
    ]
