# Generated by Django 5.2.3 on 2025-06-24 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 17, 51, 52, 12963, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 17, 51, 52, 12219, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 17, 51, 52, 11807, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 17, 51, 52, 13349, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='referalbonus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 17, 51, 52, 12598, tzinfo=datetime.timezone.utc)),
        ),
    ]
