# Generated by Django 5.2.3 on 2025-06-24 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_withdrawal_date_alter_bonus_date_alter_deposit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='referalbonus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
