# Generated by Django 5.2.3 on 2025-06-24 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_bonus_date_alter_deposit_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('ref_level', models.IntegerField(default=0)),
                ('client_status', models.CharField(max_length=50)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
