# Generated by Django 5.2.3 on 2025-06-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_referallist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='plan',
            field=models.CharField(default='Basic', max_length=100),
        ),
    ]
