# Generated by Django 5.2.3 on 2025-06-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_profit_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
