# Generated by Django 5.2.3 on 2025-06-25 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_kyc_userprofile_kyc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('swift_code', models.CharField(max_length=20)),
                ('bitcoin_address', models.CharField(max_length=200)),
                ('ethereum_address', models.CharField(max_length=200)),
                ('litecoin_address', models.CharField(max_length=200)),
                ('usdt_trc20_address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
