# Generated by Django 5.2.3 on 2025-06-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='coin',
            field=models.CharField(default='btc', max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
