# Generated by Django 5.2.3 on 2025-09-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_referallist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='type',
            field=models.CharField(default='Penalty', max_length=50),
        ),
    ]
