# Generated by Django 5.2.3 on 2025-09-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_penalty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='Withdrawalstatus',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
